### ISSUE TITLE
Some papers

### ISSUE THREAD

**Issue by onlyonewater** [SCZwangxiao/Temporal-Language-Grounding-in-videos#1]
the paper *Tripping through time: Efficient Localization of Activities in Videos * is accepted by BMVC 2020. There are also 2 papers are accepted by MM 2020, they are Jointly Cross- and Self-Modal Graph Attention Network for
Query-Based Moment Localization and Fine-grained Iterative Attention Network for Temporal
Language Localization in Videos.

**Comment by SCZwangxiao** [comment]
Thank you very much for the remindings! All three papers have been updated.
