### ISSUE TITLE
Running time comparison

### ISSUE THREAD

**Issue by liudaizong** [SCZwangxiao/Temporal-Language-Grounding-in-videos#2]
Hi, have you implemented some latest methods like LGI? I'm interested in its running time on each video, I would be very grateful if you report it to me.

**Comment by SCZwangxiao** [comment]
I‘ve reproduced LGI using the released [code](https://github.com/JonghwanMun/LGI4temporalgrounding) on RTX 2080Ti. For the charades dataset with batch_size=128, the average model inference time (forward) is 0.0019 s/video

**Comment by liudaizong** [comment]
> I‘ve reproduced LGI using the released [code](https://github.com/JonghwanMun/LGI4temporalgrounding) on RTX 2080Ti.
> For the Charades dataset with batch_size=128, the average model inference time (forward) is 0.0019 s/video.
> For the Activitynet dataset with batch_size=128, the average model inference time (forward) is 0.0026 s/video.

Thank you very much!
